Feature/sponsors
python-spain/PyConES-2018 pull request #15
Opened 2018-06-27 12:20 UTC by saruba

2018-06-27 12:21 UTC, marcosgabarda approved these changes

2018-06-27 16:24 UTC, Juanlu001 commented
¡Gracias! Me apunto echarle un vistazo a esto para mañana

2018-06-29 08:47 UTC, astrojuanlu requested changes
Falta Athento, con eso ya mergeamos!

2018-06-29 09:00 UTC, marcosgabarda commented
En nuestra defensa diré que ese patrocinador llegó después que tuvieramos esto hecho :P

2018-06-29 09:16 UTC, astrojuanlu approved these changes

2018-06-29 09:16 UTC, Juanlu001 commented
Por supuesto :P Mergeando!

2018-06-29 09:16 UTC, merged